admin:
  profile_path: /tmp/envoy.prof
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
                  timeout: 0s
          http_filters:
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                name: "mini_proxy"
                root_id: "mini_proxy"
                vm_config:
                  runtime: "envoy.wasm.runtime.v8"
                  vm_id: "mini_proxy"
                  environment_variables:
                    host_env_keys:
                    - HOSTNAME
                    - POD_NAME
                    - INSTANCE_IP
                    - ISTIO_META_WORKLOAD_NAME
                    - ISTIO_META_MESH_ID
                    - TRUST_DOMAIN
                    - POD_NAMESPACE
                    - SERVICE_ACCOUNT
                  code:
                    local:
                      filename: "/config/mini_proxy.wasm"
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: web_service
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web_service
                port_value: 8080